name: CI
       # node_modules/sfdx-cli/bin/run force:auth:jwt:grant --clientid ${{ secrets.SALESFORCE_CONSUMER_KEY }} --jwtkeyfile server.key --username ${{ secrets.SALESFORCE_DEVHUB_USERNAME}} --setdefaultdevhubusername -a devhub

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        npm install sfdx-cli
        node_modules/sfdx-cli/bin/run --version
        node_modules/sfdx-cli/bin/run plugins --core
    - name: Authenticate DevHub
      run: |
        echo "${SALESFORCE_JWT_SECRET_KEY}" > server.key
        cat server.key
        node_modules/sfdx-cli/bin/run force:auth:jwt:grant --clientid 3MVG9dZJodJWITSsDJFFP3JhlZW0ci6bdrLMVu0bdPOjqB.EMlucbiMf0MYwh.kBiw.mpy90jjNyrOGw6Cqks  --jwtkeyfile server.key  --username msingh@demoorg.com  --setdefaultdevhubusername -a devhub
    - name: Create Scratch Org
      run: node_modules/sfdx-cli/bin/run force:org:create --targetdevhubusername devhub --setdefaultusername --definitionfile config/project-scratch-def.json --setalias ciorg --durationdays 1
    - name: Deploy source
      run: node_modules/sfdx-cli/bin/run force:source:push
    - name: Run Apex test
      run: node_modules/sfdx-cli/bin/run force:apex:test:run --codecoverage --resultformat human
    - name: Delete Scratch Org
      run: node_modules/sfdx-cli/bin/run force:org:delete --noprompt
    
